### ISSUE TITLE
I am getting this error when I am clicking on Users

### ISSUE THREAD

**Issue by adetheprince** [Anni1123/SocialMediaApp#4]
The app closes with error and chat is empty always, I tried to create but cant see any.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.LearnBravanese.Kids, PID: 8283
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at com.example.socialmediaapp.fragments.UsersFragment$1.onDataChange(UsersFragment.java:79)
        at com.google.firebase.database.core.ValueEventRegistration.fireEvent(com.google.firebase:firebase-database@@19.0.0:75)
        at com.google.firebase.database.core.view.DataEvent.fire(com.google.firebase:firebase-database@@19.0.0:63)
        at com.google.firebase.database.core.view.EventRaiser$1.run(com.google.firebase:firebase-database@@19.0.0:55)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by adetheprince** [comment]
I am sure my google Json is wrong any help please?

**Comment by Anni1123** [comment]
Yes , I found  that what you are saying is right..This is happening because some users just registered but didnt updated their name in profile section
